### ISSUE TITLE
unable to build - errors

### ISSUE THREAD

**Issue by alphathegeek** [jjsch-dev/pico_i2c_sniffer#2] opened 2021-08-11 02:57 UTC
unable to build with following error: 

-using latest PICO_SDK from git
-using latest tinyUSB and other libraries from git [ --recursive from PICO_SDK ] 

/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/i2c_sniffer_pio.dir/home/owner/RaspberryPi/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj: in function `__wrap_putchar':
stdio.c:(.text.__wrap_putchar+0x10): undefined reference to `stdout_serialize_begin'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: stdio.c:(.text.__wrap_putchar+0x56): undefined reference to `stdout_serialize_end'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/i2c_sniffer_pio.dir/home/owner/RaspberryPi/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj: in function `__wrap_puts':
stdio.c:(.text.__wrap_puts+0x16): undefined reference to `stdout_serialize_begin'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: stdio.c:(.text.__wrap_puts+0x9c): undefined reference to `stdout_serialize_end'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/i2c_sniffer_pio.dir/home/owner/RaspberryPi/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj: in function `__wrap_vprintf':
stdio.c:(.text.__wrap_vprintf+0xc): undefined reference to `stdout_serialize_begin'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: stdio.c:(.text.__wrap_vprintf+0x94): undefined reference to `stdout_serialize_end'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/i2c_sniffer_pio.dir/build.make:717: i2c_sniffer_pio.elf] Error 1
make[1]: *** [CMakeFiles/Makefile2:1569: CMakeFiles/i2c_sniffer_pio.dir/all] Error 2

**Comment by jjsch-dev** [comment] 2021-08-11 14:38
@alphathegeek Hi, thanks for the report, I'm going to try the latest version of the SDK and I'll tell you.

**Comment by alphathegeek** [comment] 2021-08-11 14:46
> @alphathegeek Hi, thanks for the report, I'm going to try the latest version of the SDK and I'll tell you.

Thanks!

**Comment by alphathegeek** [comment] 2021-08-11 14:50
BTW: Tried the binary, worked of course, neat project, makes a great "logicsniffer" that I can use! Tried on a unknown thermal FIR sensor to get some information out of it.

**Comment by jjsch-dev** [comment] 2021-08-11 20:49
> BTW: Tried the binary, worked of course, neat project, makes a great "logicsniffer" that I can use! Tried on a unknown thermal FIR sensor to get some information out of it.

I'm glad that at least with the bin you were able to test the sniffer.

**Comment by jjsch-dev** [comment] 2021-08-11 21:17
@alphathegeek  Sorry for the delay in responding, the problem was in a refactoring that they did in the SDK, I [reported](https://github.com/raspberrypi/pico-sdk/issues/490) it and they already corrected it but it is not yet in the master.

Until it goes up in the master, there are three ways to solve it, one is to download the [development](https://github.com/raspberrypi/pico-sdk/tree/develop) version, the other is to put the fix that I suggest in the issue (with which I compile this version), and the other is to put the [fix](https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/pico_stdio/stdio.c) that they suggest that it is simpler.

Could you try some of the suggestions? Just next weekend I will have time available to test the development version of the SDK and start testing.

**Comment by alphathegeek** [comment] 2021-08-11 23:22
Can do, will give it a try later tonight. Many thanks for your help.

**Comment by alphathegeek** [comment] 2021-08-12 02:11
Just another thought. You mention that in the readme you can't really check for the max sampling rate and framing errors, etc to get a sense of the max speed. I've got a raspi v3, so I can generate a test that does an i2c scan. That would generate 127 addresses, which would see if the code has any timing dependencies. it can also go  up to 4Mhz.

**Comment by jjsch-dev** [comment] 2021-08-12 13:24
What a good idea, when you do, please tell me the results.

**Comment by alphathegeek** [comment] 2021-08-14 03:28
> What a good idea, when you do, please tell me the results.

Thanks!

I tried the "i2cdetect -y 1" on the raspberry pi 3, with a default i2c rate of 1Mhz. Without any devices connected to the i2c line, to try to test the nack/ack detection. Works fine! 117 addresses tested 0x03 - 0x77, I did not try the weirder addresses that violate the i2c spec.

I can try the 1Mhz and 4Mhz baud rates. Unable to attach scope pictures, since my scope is a lowly Fluke 99B, making it hard to get a capture.

**Comment by jjsch-dev** [comment] 2021-08-14 18:00
@alphathegeek I did not know the i2cdectec tool, and it is good that the sniffer works with 1Mhz, I am waiting for the 4Mhz results.

**Comment by csBlueChip** [comment] 2022-09-08 16:09
I realise we've now got two issues running in the same thread. But I wish to confirm that you may now close the *original* issue, as your fix is apparently absorbed.

I just had : same error ... `~/pico-sdk/`  `git pull ; git submodule update` ... error gone
[*see post date*]

**Comment by jjsch-dev** [comment] 2022-09-08 16:49
Hello @csBlueChip, I will try your suggestion to validate the solution. Thank you

**Comment by jjsch-dev** [comment] 2022-09-09 13:24
@csBlueChip Thanks for the advice, I tried with the latest version of the SDK as you suggest and the build does not fail.

**Comment by jjsch-dev** [comment] 2022-09-09 13:35
the problem is fixed with the latest version of the SDK.

**Closed as completed by jjsch-dev** 2022-09-09 13:35 UTC
